export const ROUTES = {
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  EMAIL_VERIFICATION: '/email-verification/:key',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:uid/:key',
  USER_TYPE: '/select-user-type',
  DEGREE_SELECT: '/degree-select',
  SUCCESSFUL_SIGN_UP: '/successful-signup',
  HOME: '/home',
  REVIEW: '/deck/:deckId/review',
  DASHBOARD: '/dashboard',
  FLASHCARD: '/flashcard',
  PDF_IMPORT: '/pdf-import',
  ANKI_IMPORT: '/anki-import',
  DECKS: '/decks',
  DECKS_DECK: '/decks/:deckParam?',
  DECKS_CARD: '/decks/:deckParam/cards/:cardId?',
  LEADERBOARD: '/leaderboard',
};
